// src/components/WorkspacePicker.tsx
import { useState, useEffect, useCallback, useRef, useMemo } from "react";
import { useWorkspaceStore } from "../stores/workspace";
import { openWorkspace, createWorkspace, deleteWorkspace } from "../lib/tauri";
import { useToastStore } from "./Toast";
import type { WorkspaceMeta } from "../lib/tauri";
import { useCommandStore } from "../stores/commands";
import { useFocusContextStore } from "../stores/focus-context";

function relativeTime(iso: string): string {
  const now = Date.now();
  const then = new Date(iso).getTime();
  const diffMs = now - then;
  const diffMin = Math.floor(diffMs / 60_000);
  if (diffMin < 60) return diffMin <= 1 ? "just now" : `${diffMin}m ago`;
  const diffHr = Math.floor(diffMin / 60);
  if (diffHr < 24) return `${diffHr}h ago`;
  const diffDays = Math.floor(diffHr / 24);
  if (diffDays < 30) return `${diffDays}d ago`;
  const diffMonths = Math.floor(diffDays / 30);
  return `${diffMonths}mo ago`;
}

export function WorkspacePicker() {
  const workspaces = useWorkspaceStore((s) => s.workspaces);
  const sorted = useMemo(
    () =>
      workspaces.toSorted(
        (a, b) => new Date(b.last_opened).getTime() - new Date(a.last_opened).getTime(),
      ),
    [workspaces],
  );
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [creatingNew, setCreatingNew] = useState(false);
  const [newName, setNewName] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const handleOpen = useCallback(async (ws: WorkspaceMeta) => {
    try {
      const meta = await openWorkspace(ws.id);
      useWorkspaceStore.getState().setActiveWorkspace(meta);
    } catch (err) {
      useToastStore
        .getState()
        .addToast(
          `Failed to open workspace: ${err instanceof Error ? err.message : String(err)}`,
          "error",
        );
    }
  }, []);

  useEffect(() => {
    useFocusContextStore.getState().setActiveRegion("workspace-picker");
  }, []);

  useEffect(() => {
    useCommandStore.getState().registerCommand({
      id: "workspace.create",
      label: "New Workspace",
      shortcut: "Mod+N",
      context: "workspace-picker" as const,
      execute: () => setCreatingNew(true),
    });
    return () => useCommandStore.getState().unregisterCommand("workspace.create");
  }, []);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (creatingNew) return;

      if (e.key === "ArrowDown") {
        e.preventDefault();
        setSelectedIndex((i) => (i + 1) % sorted.length);
      } else if (e.key === "ArrowUp") {
        e.preventDefault();
        setSelectedIndex((i) => (i - 1 + sorted.length) % sorted.length);
      } else if (e.key === "Enter") {
        if (sorted[selectedIndex]) handleOpen(sorted[selectedIndex]);
      } else if ((e.key === "Delete" || e.key === "Backspace") && sorted.length > 0) {
        e.preventDefault();
        const ws = sorted[selectedIndex];
        if (ws) {
          deleteWorkspace(ws.id)
            .then(() => {
              const remaining = useWorkspaceStore
                .getState()
                .workspaces.filter((w) => w.id !== ws.id);
              useWorkspaceStore.getState().setWorkspaces(remaining);
              setSelectedIndex((i) =>
                remaining.length === 0 ? 0 : Math.min(i, remaining.length - 1),
              );
              useToastStore.getState().addToast(`Deleted "${ws.name}"`, "info");
            })
            .catch((err) => {
              useToastStore
                .getState()
                .addToast(
                  `Failed to delete workspace: ${err instanceof Error ? err.message : String(err)}`,
                  "error",
                );
            });
        }
      }
    };

    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [creatingNew, sorted, selectedIndex, handleOpen]);

  useEffect(() => {
    if (creatingNew) inputRef.current?.focus();
  }, [creatingNew]);

  const handleCreate = useCallback(async (name: string) => {
    try {
      const id = await createWorkspace(name);
      const meta = await openWorkspace(id);
      useWorkspaceStore.getState().setActiveWorkspace(meta);
    } catch (err) {
      useToastStore
        .getState()
        .addToast(
          `Failed to create workspace: ${err instanceof Error ? err.message : String(err)}`,
          "error",
        );
    }
  }, []);

  const handleInputKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (e.key === "Escape") {
        setCreatingNew(false);
        setNewName("");
      } else if (e.key === "Enter" && newName.trim()) {
        handleCreate(newName.trim());
      }
    },
    [newName, handleCreate],
  );

  return (
    <div
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        width: "100%",
      }}
    >
      <div style={{ width: 320, display: "flex", flexDirection: "column", gap: 12 }}>
        <div>
          <div
            style={{
              fontSize: 18,
              fontWeight: 600,
              color: "var(--color-fg-heading)",
            }}
          >
            Open a workspace
          </div>
          <div
            style={{
              fontSize: 12,
              color: "var(--color-fg-muted)",
              marginTop: 4,
            }}
          >
            Or create a new one to get started
          </div>
        </div>

        <div
          role="listbox"
          style={{
            border: "1px solid var(--color-border-default)",
            borderRadius: 4,
            overflow: "hidden",
          }}
        >
          {creatingNew && (
            <input
              ref={inputRef}
              type="text"
              value={newName}
              onChange={(e) => setNewName(e.target.value)}
              onKeyDown={handleInputKeyDown}
              placeholder="Workspace name..."
              style={{
                width: "100%",
                padding: "8px 12px",
                background: "var(--color-bg-base)",
                border: "none",
                borderBottom: "1px solid var(--color-border-default)",
                color: "var(--color-fg-heading)",
                fontSize: 13,
                outline: "none",
                boxSizing: "border-box",
              }}
            />
          )}
          {sorted.length === 0 ? (
            <div
              style={{
                padding: "8px 12px",
                fontSize: 13,
                color: "var(--color-fg-muted)",
              }}
            >
              No workspaces yet
            </div>
          ) : (
            sorted.map((ws, i) => (
              <div
                key={ws.id}
                role="option"
                aria-selected={i === selectedIndex}
                onClick={() => setSelectedIndex(i)}
                onDoubleClick={() => handleOpen(ws)}
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  padding: "8px 12px",
                  cursor: "default",
                  borderBottom:
                    i < sorted.length - 1 ? "1px solid var(--color-border-default)" : "none",
                  background: i === selectedIndex ? "var(--color-bg-selected)" : undefined,
                  color:
                    i === selectedIndex ? "var(--color-fg-heading)" : "var(--color-fg-default)",
                  minHeight: 34,
                }}
              >
                <span style={{ fontSize: 13 }}>{ws.name}</span>
                <span
                  style={{
                    fontSize: 11,
                    color: "var(--color-fg-disabled)",
                  }}
                >
                  {relativeTime(ws.last_opened)}
                </span>
              </div>
            ))
          )}
        </div>

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <span
            onClick={() => setCreatingNew(true)}
            style={{
              fontSize: 12,
              color: "var(--color-accent-text)",
            }}
          >
            New workspace
          </span>
          <div style={{ display: "flex", gap: 12 }}>
            <span
              style={{
                color: "var(--color-fg-disabled)",
                fontSize: 10,
                fontFamily: "var(--font-mono)",
              }}
            >
              <span
                style={{ background: "var(--color-bg-hover)", padding: "1px 4px", borderRadius: 2 }}
              >
                {"↑↓"}
              </span>
              {" navigate"}
            </span>
            <span
              style={{
                color: "var(--color-fg-disabled)",
                fontSize: 10,
                fontFamily: "var(--font-mono)",
              }}
            >
              <span
                style={{ background: "var(--color-bg-hover)", padding: "1px 4px", borderRadius: 2 }}
              >
                {"↵"}
              </span>
              {" open"}
            </span>
            <span
              style={{
                color: "var(--color-fg-disabled)",
                fontSize: 10,
                fontFamily: "var(--font-mono)",
              }}
            >
              <span
                style={{ background: "var(--color-bg-hover)", padding: "1px 4px", borderRadius: 2 }}
              >
                {"⌘N"}
              </span>
              {" new"}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/components/workspace/WorkspacePicker.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { workspaceStore } from "../../stores/workspace.svelte";
  import { toastStore } from "../../stores/toast.svelte";
  import { commandStore } from "../../stores/commands.svelte";
  import { focusContextStore } from "../../stores/focus-context.svelte";
  import {
    openWorkspace,
    createWorkspace,
    deleteWorkspace,
  } from "../../lib/tauri";
  import type { WorkspaceMeta } from "../../lib/tauri";

  function relativeTime(iso: string): string {
    const now = Date.now();
    const then = new Date(iso).getTime();
    const diffMs = now - then;
    const diffMin = Math.floor(diffMs / 60_000);
    if (diffMin < 60) return diffMin <= 1 ? "just now" : `${diffMin}m ago`;
    const diffHr = Math.floor(diffMin / 60);
    if (diffHr < 24) return `${diffHr}h ago`;
    const diffDays = Math.floor(diffHr / 24);
    if (diffDays < 30) return `${diffDays}d ago`;
    const diffMonths = Math.floor(diffDays / 30);
    return `${diffMonths}mo ago`;
  }

  let selectedIndex = $state(0);
  let creatingNew = $state(false);
  let newName = $state("");
  let inputEl: HTMLInputElement | undefined = $state();

  const sorted = $derived(
    [...workspaceStore.workspaces].sort(
      (a, b) =>
        new Date(b.last_opened).getTime() - new Date(a.last_opened).getTime(),
    ),
  );

  onMount(() => {
    focusContextStore.setActiveRegion("workspace-picker");

    commandStore.registerCommand({
      id: "workspace.create",
      label: "New Workspace",
      shortcut: "Mod+N",
      context: "workspace-picker" as const,
      execute: () => {
        creatingNew = true;
      },
    });

    return () => {
      commandStore.unregisterCommand("workspace.create");
    };
  });

  $effect(() => {
    if (creatingNew) {
      // Need a tick for the DOM to render before focusing
      setTimeout(() => inputEl?.focus(), 0);
    }
  });

  async function handleOpen(ws: WorkspaceMeta) {
    try {
      const meta = await openWorkspace(ws.id);
      workspaceStore.setActiveWorkspace(meta);
    } catch (err) {
      toastStore.addToast(
        `Failed to open workspace: ${err instanceof Error ? err.message : String(err)}`,
        "error",
      );
    }
  }

  async function handleCreate(name: string) {
    try {
      const id = await createWorkspace(name);
      const meta = await openWorkspace(id);
      workspaceStore.setActiveWorkspace(meta);
    } catch (err) {
      toastStore.addToast(
        `Failed to create workspace: ${err instanceof Error ? err.message : String(err)}`,
        "error",
      );
    }
  }

  function handleInputKeyDown(e: KeyboardEvent) {
    if (e.key === "Escape") {
      creatingNew = false;
      newName = "";
    } else if (e.key === "Enter" && newName.trim()) {
      handleCreate(newName.trim());
    }
  }

  function handleWindowKeyDown(e: KeyboardEvent) {
    if (creatingNew) return;

    if (e.key === "ArrowDown") {
      e.preventDefault();
      if (sorted.length > 0)
        selectedIndex = (selectedIndex + 1) % sorted.length;
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      if (sorted.length > 0)
        selectedIndex = (selectedIndex - 1 + sorted.length) % sorted.length;
    } else if (e.key === "Enter") {
      if (sorted[selectedIndex]) handleOpen(sorted[selectedIndex]!);
    } else if (
      (e.key === "Delete" || e.key === "Backspace") &&
      sorted.length > 0
    ) {
      e.preventDefault();
      const ws = sorted[selectedIndex];
      if (ws) {
        deleteWorkspace(ws.id)
          .then(() => {
            const remaining = workspaceStore.workspaces.filter(
              (w) => w.id !== ws.id,
            );
            workspaceStore.setWorkspaces(remaining);
            selectedIndex =
              remaining.length === 0
                ? 0
                : Math.min(selectedIndex, remaining.length - 1);
            toastStore.addToast(`Deleted "${ws.name}"`, "info");
          })
          .catch((err) => {
            toastStore.addToast(
              `Failed to delete workspace: ${err instanceof Error ? err.message : String(err)}`,
              "error",
            );
          });
      }
    }
  }
</script>

<svelte:window onkeydown={handleWindowKeyDown} />

<div
  style="display: flex; align-items: center; justify-content: center; height: 100vh; width: 100%;"
>
  <div style="width: 320px; display: flex; flex-direction: column; gap: 12px;">
    <div>
      <div
        style="font-size: 18px; font-weight: 600; color: var(--color-fg-heading);"
      >
        Open a workspace
      </div>
      <div
        style="font-size: 12px; color: var(--color-fg-muted); margin-top: 4px;"
      >
        Or create a new one to get started
      </div>
    </div>

    <div
      role="listbox"
      style="border: 1px solid var(--color-border-default); border-radius: 4px; overflow: hidden;"
    >
      {#if creatingNew}
        <input
          bind:this={inputEl}
          type="text"
          bind:value={newName}
          onkeydown={handleInputKeyDown}
          placeholder="Workspace name..."
          style="width: 100%; padding: 8px 12px; background: var(--color-bg-base); border: none; border-bottom: 1px solid var(--color-border-default); color: var(--color-fg-heading); font-size: 13px; outline: none; box-sizing: border-box;"
        />
      {/if}
      {#if sorted.length === 0}
        <div
          style="padding: 8px 12px; font-size: 13px; color: var(--color-fg-muted);"
        >
          No workspaces yet
        </div>
      {:else}
        {#each sorted as ws, i (ws.id)}
          <div
            role="option"
            tabindex={-1}
            aria-selected={i === selectedIndex}
            onclick={() => {
              selectedIndex = i;
            }}
            onkeydown={(e) => {
              if (e.key === "Enter") handleOpen(ws);
            }}
            ondblclick={() => handleOpen(ws)}
            style="display: flex; align-items: center; justify-content: space-between; padding: 8px 12px; cursor: default; border-bottom: {i <
            sorted.length - 1
              ? '1px solid var(--color-border-default)'
              : 'none'}; background: {i === selectedIndex
              ? 'var(--color-bg-selected)'
              : 'transparent'}; color: {i === selectedIndex
              ? 'var(--color-fg-heading)'
              : 'var(--color-fg-default)'}; min-height: 34px;"
          >
            <span style="font-size: 13px;">{ws.name}</span>
            <span style="font-size: 11px; color: var(--color-fg-disabled);">
              {relativeTime(ws.last_opened)}
            </span>
          </div>
        {/each}
      {/if}
    </div>

    <div
      style="display: flex; align-items: center; justify-content: space-between;"
    >
      <button
        type="button"
        onclick={() => {
          creatingNew = true;
        }}
        style="font-size: 12px; color: var(--color-accent-text); background: none; border: none; padding: 0; cursor: pointer; font-family: inherit;"
      >
        New workspace
      </button>
      <div style="display: flex; gap: 12px;">
        <span
          style="color: var(--color-fg-disabled); font-size: 10px; font-family: var(--font-mono);"
        >
          <span
            style="background: var(--color-bg-hover); padding: 1px 4px; border-radius: 2px;"
          >
            {"\u2191\u2193"}
          </span>
          {" navigate"}
        </span>
        <span
          style="color: var(--color-fg-disabled); font-size: 10px; font-family: var(--font-mono);"
        >
          <span
            style="background: var(--color-bg-hover); padding: 1px 4px; border-radius: 2px;"
          >
            {"\u21B5"}
          </span>
          {" open"}
        </span>
        <span
          style="color: var(--color-fg-disabled); font-size: 10px; font-family: var(--font-mono);"
        >
          <span
            style="background: var(--color-bg-hover); padding: 1px 4px; border-radius: 2px;"
          >
            {"\u2318N"}
          </span>
          {" new"}
        </span>
      </div>
    </div>
  </div>
</div>
