// src/components/sidebar/ContextMenu.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import type { MenuItem } from "../../stores/types";

  interface Props {
    x: number;
    y: number;
    items: MenuItem[];
    onSelect: (id: string) => void;
    onClose: () => void;
  }

  let { x, y, items, onSelect, onClose }: Props = $props();

  let menuEl: HTMLDivElement | undefined = $state();
  let offsetX = $state(0);
  let offsetY = $state(0);
  let adjustedX = $derived(x + offsetX);
  let adjustedY = $derived(y + offsetY);

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === "Escape") onClose();
  }

  function handleMousedown(e: MouseEvent) {
    if (menuEl && !menuEl.contains(e.target as Node)) {
      onClose();
    }
  }

  onMount(() => {
    window.addEventListener("keydown", handleKeydown);
    document.addEventListener("mousedown", handleMousedown);

    // Viewport-aware positioning: flip if menu overflows
    if (menuEl) {
      const rect = menuEl.getBoundingClientRect();
      if (rect.right > window.innerWidth) {
        offsetX = -rect.width;
      }
      if (rect.bottom > window.innerHeight) {
        offsetY = -rect.height;
      }
    }
  });

  onDestroy(() => {
    window.removeEventListener("keydown", handleKeydown);
    document.removeEventListener("mousedown", handleMousedown);
  });
</script>

<div
  bind:this={menuEl}
  class="fixed z-[200] min-w-[180px] rounded-[8px] border border-border-strong bg-bg-elevated p-1 shadow-[var(--shadow-md)]"
  style="left: {adjustedX}px; top: {adjustedY}px;"
  data-testid="context-menu"
>
  {#each items as item (item.id)}
    {#if item.separator}
      <div class="mx-[6px] my-1 h-px bg-border-default"></div>
    {:else}
      <button
        type="button"
        class="flex w-full items-center gap-2 rounded-[5px] px-[10px] py-[6px] text-left text-[12px]
          {item.disabled
          ? 'cursor-not-allowed text-fg-disabled hover:bg-transparent'
          : item.danger
            ? 'cursor-default text-error hover:bg-error/10'
            : 'cursor-default text-fg-default hover:bg-bg-hover'}"
        onclick={() => {
          if (!item.disabled) onSelect(item.id);
        }}
        disabled={item.disabled}
      >
        {#if item.icon}
          <item.icon size={13} class="opacity-70 shrink-0" />
        {/if}
        {item.label}
        {#if item.shortcut}
          <span
            class="ml-auto text-[10px] text-fg-disabled font-[family-name:var(--font-mono)]"
            >{item.shortcut}</span
          >
        {/if}
      </button>
    {/if}
  {/each}
</div>

// src/components/ContextMenu.tsx
import { useEffect, useRef, useState, useCallback } from "react";

export type MenuItem =
  | { label: string; action: string; type?: undefined }
  | { type: "separator"; label?: undefined; action?: undefined };

type ContextMenuProps = {
  x: number;
  y: number;
  items: MenuItem[];
  onAction: (action: string) => void;
  onClose: () => void;
};

export function ContextMenu({ x, y, items, onAction, onClose }: ContextMenuProps) {
  const menuRef = useRef<HTMLDivElement>(null);
  const actionItems = items.filter(
    (item): item is MenuItem & { action: string } => item.type !== "separator",
  );
  const [focusIndex, setFocusIndex] = useState(0);

  // Click outside to dismiss
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        onClose();
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [onClose]);

  // Auto-focus menu on mount
  useEffect(() => {
    menuRef.current?.focus();
  }, []);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      switch (e.key) {
        case "Escape":
          e.preventDefault();
          onClose();
          break;
        case "ArrowDown":
          e.preventDefault();
          setFocusIndex((i) => (i + 1) % actionItems.length);
          break;
        case "ArrowUp":
          e.preventDefault();
          setFocusIndex((i) => (i - 1 + actionItems.length) % actionItems.length);
          break;
        case "Enter":
          e.preventDefault();
          if (actionItems[focusIndex]) {
            onAction(actionItems[focusIndex].action);
            onClose();
          }
          break;
      }
    },
    [onClose, onAction, actionItems, focusIndex],
  );

  // Clamp position to viewport
  const style: React.CSSProperties = {
    position: "fixed",
    left: Math.min(x, window.innerWidth - 200),
    top: Math.min(y, window.innerHeight - items.length * 28 - 16),
    background: "var(--color-bg-hover)",
    border: "1px solid var(--color-border-default)",
    borderRadius: 4,
    padding: "4px 0",
    minWidth: 160,
    zIndex: 1000,
    outline: "none",
  };

  let actionIndex = -1;

  return (
    <div ref={menuRef} role="menu" tabIndex={0} onKeyDown={handleKeyDown} style={style}>
      {items.map((item, i) => {
        if (item.type === "separator") {
          return (
            <div
              key={`sep-${i}`}
              style={{
                height: 1,
                background: "var(--color-border-default)",
                margin: "4px 0",
              }}
            />
          );
        }
        actionIndex++;
        const isFocused = actionIndex === focusIndex;
        return (
          <div
            key={item.action}
            role="menuitem"
            onClick={() => {
              onAction(item.action);
              onClose();
            }}
            style={{
              height: 28,
              display: "flex",
              alignItems: "center",
              padding: "0 12px",
              fontSize: 13,
              cursor: "default",
              color: isFocused ? "var(--color-fg-heading)" : "var(--color-fg-default)",
              background: isFocused ? "var(--color-bg-active)" : "transparent",
            }}
          >
            {item.label}
          </div>
        );
      })}
    </div>
  );
}
