// src/components/TabBar.svelte
<script lang="ts">
  import { editorStore } from "../stores/editor.svelte";
</script>

{#if editorStore.openTabs.length > 0}
  <div
    class="flex overflow-x-auto"
    style="height: 32px; border-bottom: 1px solid var(--color-border-default);"
  >
    {#each editorStore.openTabs as tab (tab.path)}
      {@const isActive = tab.path === editorStore.activeTab}
      {@const isDirty = editorStore.dirtyTabs.has(tab.path)}
      <div
        onclick={() => editorStore.setActiveTab(tab.path)}
        class="interactive group flex items-center gap-2 px-3"
        style="font-size: 13px; color: {isActive ? 'var(--color-fg-heading)' : 'var(--color-fg-muted)'}; border-bottom: {isActive ? '1px solid var(--color-accent)' : '1px solid transparent'}; white-space: nowrap;"
      >
        <span>{tab.name}</span>
        {#if isDirty}
          <span
            style="width: 6px; height: 6px; border-radius: 50%; background: var(--color-warning); flex-shrink: 0;"
          ></span>
        {/if}
        <span
          role="button"
          tabindex="0"
          onclick={(e) => { e.stopPropagation(); editorStore.closeTab(tab.path); }}
          onkeydown={(e) => { if (e.key === 'Enter') { e.stopPropagation(); editorStore.closeTab(tab.path); } }}
          class="interactive opacity-0 group-hover:opacity-100"
          style="font-size: 10px; color: var(--color-fg-muted); transition: opacity 100ms ease-out;"
        >
          &times;
        </span>
      </div>
    {/each}
  </div>
{/if}

// src/components/TabBar.tsx
import { useEditorStore } from "../stores/editor";

export function TabBar() {
  const { openTabs, activeTab, dirtyTabs, setActiveTab, closeTab } = useEditorStore();

  if (openTabs.length === 0) return null;

  return (
    <div
      className="flex overflow-x-auto"
      style={{
        height: 32,
        borderBottom: "1px solid var(--color-border-default)",
      }}
    >
      {openTabs.map((tab) => {
        const isActive = tab.path === activeTab;
        const isDirty = dirtyTabs.has(tab.path);

        return (
          <div
            key={tab.path}
            onClick={() => setActiveTab(tab.path)}
            className="interactive group flex items-center gap-2 px-3"
            style={{
              fontSize: 13,
              color: isActive ? "var(--color-fg-heading)" : "var(--color-fg-muted)",
              borderBottom: isActive ? "1px solid var(--color-accent)" : "1px solid transparent",
              whiteSpace: "nowrap",
            }}
          >
            <span>{tab.name}</span>
            {isDirty && (
              <span
                style={{
                  width: 6,
                  height: 6,
                  borderRadius: "50%",
                  background: "var(--color-warning)",
                  flexShrink: 0,
                }}
              />
            )}
            <span
              onClick={(e) => {
                e.stopPropagation();
                closeTab(tab.path);
              }}
              className="interactive opacity-0 group-hover:opacity-100"
              style={{
                fontSize: 10,
                color: "var(--color-fg-muted)",
                transition: "opacity 100ms ease-out",
              }}
            >
              ×
            </span>
          </div>
        );
      })}
    </div>
  );
}
