// src/components/shared/Toast.svelte
<!-- src/components/Toast.svelte -->
<script lang="ts">
  import { toastStore } from "../stores/toast.svelte";

  const TYPE_COLORS: Record<string, string> = {
    success: "var(--color-success)",
    error: "var(--color-error)",
    info: "var(--color-accent)",
  };
</script>

{#if toastStore.toasts.length > 0}
  <div
    style="position: fixed; bottom: 32px; right: 16px; z-index: 1000; display: flex; flex-direction: column; gap: 8px;"
  >
    {#each toastStore.toasts as toast (toast.id)}
      <div
        style="background: var(--color-bg-active); border: 1px solid var(--color-border-default); border-left: 3px solid {TYPE_COLORS[
          toast.type
        ]}; border-radius: 4px; padding: 8px 12px; font-size: 13px; color: var(--color-fg-default); display: flex; align-items: center; gap: 8px; max-width: 360px; animation: toast-in 150ms ease-out;"
      >
        <span style="flex: 1;">{toast.message}</span>
        {#if toast.action}
          <button
            onclick={() => {
              toast.action!.onClick();
              toastStore.removeToast(toast.id);
            }}
            class="interactive"
            style="background: none; border: none; color: var(--color-accent-text); font-size: 12px; padding: 2px 6px;"
          >
            {toast.action.label}
          </button>
        {/if}
        <span
          role="button"
          tabindex="0"
          onclick={() => toastStore.removeToast(toast.id)}
          onkeydown={(e) => {
            if (e.key === "Enter") toastStore.removeToast(toast.id);
          }}
          class="interactive"
          style="color: var(--color-fg-muted); font-size: 10px;"
        >
          ×
        </span>
      </div>
    {/each}
  </div>
{/if}

// src/components/Toast.tsx
import { create } from "zustand";

type ToastType = "success" | "error" | "info";

type Toast = {
  id: string;
  message: string;
  type: ToastType;
  action?: { label: string; onClick: () => void } | undefined;
};

type ToastState = {
  toasts: Toast[];
  addToast: (message: string, type: ToastType, action?: Toast["action"], duration?: number) => void;
  removeToast: (id: string) => void;
};

export const useToastStore = create<ToastState>((set, get) => ({
  toasts: [],
  addToast: (message, type, action, duration) => {
    const id = crypto.randomUUID();
    const toast: Toast = { id, message, type };
    if (action) toast.action = action;
    set({ toasts: [...get().toasts, toast] });
    setTimeout(() => get().removeToast(id), duration ?? 4000);
  },
  removeToast: (id) => set({ toasts: get().toasts.filter((t) => t.id !== id) }),
}));

const TYPE_COLORS: Record<ToastType, string> = {
  success: "var(--color-success)",
  error: "var(--color-error)",
  info: "var(--color-accent)",
};

export function ToastContainer() {
  const { toasts, removeToast } = useToastStore();

  if (toasts.length === 0) return null;

  return (
    <div
      style={{
        position: "fixed",
        bottom: 32,
        right: 16,
        zIndex: 1000,
        display: "flex",
        flexDirection: "column",
        gap: 8,
      }}
    >
      {toasts.map((toast) => (
        <div
          key={toast.id}
          style={{
            background: "var(--color-bg-active)",
            border: "1px solid var(--color-border-default)",
            borderLeft: `3px solid ${TYPE_COLORS[toast.type]}`,
            borderRadius: 4,
            padding: "8px 12px",
            fontSize: 13,
            color: "var(--color-fg-default)",
            display: "flex",
            alignItems: "center",
            gap: 8,
            maxWidth: 360,
            animation: "toast-in 150ms ease-out",
          }}
        >
          <span style={{ flex: 1 }}>{toast.message}</span>
          {toast.action && (
            <button
              onClick={() => {
                toast.action!.onClick();
                removeToast(toast.id);
              }}
              className="interactive"
              style={{
                background: "none",
                border: "none",
                color: "var(--color-accent-text)",
                fontSize: 12,
                padding: "2px 6px",
              }}
            >
              {toast.action.label}
            </button>
          )}
          <span
            onClick={() => removeToast(toast.id)}
            className="interactive"
            style={{
              color: "var(--color-fg-muted)",
              fontSize: 10,
            }}
          >
            ×
          </span>
        </div>
      ))}
    </div>
  );
}
