// apps/web/src/components/workspace-switcher.tsx
import { useState, useRef, useEffect } from "react";
import { ChevronDown, Plus, Circle } from "lucide-react";
import { useWs } from "../hooks/use-ws";
import { useWorkspaceStore } from "../stores/workspace-store";
import { isElectron } from "../env";
import type { Workspace } from "@emergent/contracts";

const statusColor: Record<string, string> = {
  connected: "text-green-400",
  disconnected: "text-neutral-500",
  error: "text-red-400",
};

export function WorkspaceSwitcher() {
  const [open, setOpen] = useState(false);
  const [workspaces, setWorkspaces] = useState<Workspace[]>([]);
  const { sendRpc } = useWs();
  const { activeWorkspaceId, setActiveWorkspaceId } = useWorkspaceStore();
  const ref = useRef<HTMLDivElement>(null);

  function refreshWorkspaces() {
    sendRpc("workspace.list")
      .then((data) => setWorkspaces(data as Workspace[]))
      .catch(() => {});
  }

  useEffect(() => {
    refreshWorkspaces();
  }, [sendRpc]);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) {
        setOpen(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const active = workspaces.find((w) => w.id === activeWorkspaceId);

  function handleSelect(id: string) {
    setActiveWorkspaceId(id);
    sendRpc("workspace.setActive", { id }).catch(() => {});
    setOpen(false);
  }

  async function handleAddWorkspace() {
    let folderPath: string | null = null;

    if (isElectron) {
      folderPath = await (window as DesktopWindow).desktopBridge.pickFolder();
    } else {
      folderPath = prompt("Enter project path:");
    }

    if (!folderPath) return;

    try {
      const result = (await sendRpc("workspace.add", {
        path: folderPath,
      })) as Workspace;
      setActiveWorkspaceId(result.id);
      refreshWorkspaces();
    } catch {
      // workspace.add failed (e.g. no .overstory/ directory)
    }

    setOpen(false);
  }

  return (
    <div ref={ref} className="relative min-w-0">
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1.5 text-sm text-neutral-200 hover:text-neutral-100 transition-colors"
      >
        <span className="truncate font-semibold">
          {active?.name ?? "Select workspace"}
        </span>
        <ChevronDown
          className={`h-3.5 w-3.5 shrink-0 text-neutral-400 transition-transform ${open ? "rotate-180" : ""}`}
        />
      </button>

      {open && (
        <div className="absolute left-2 top-full z-50 mt-2 w-56 rounded-lg border border-neutral-700 bg-neutral-800 py-1 shadow-xl">
          {workspaces.map((ws) => (
            <button
              key={ws.id}
              onClick={() => handleSelect(ws.id)}
              className={`flex w-full items-center gap-2 px-3 py-2 text-sm transition-colors hover:bg-neutral-700 ${
                ws.id === activeWorkspaceId
                  ? "text-neutral-100 bg-neutral-700/50"
                  : "text-neutral-300"
              }`}
            >
              <Circle
                className={`h-2 w-2 shrink-0 fill-current ${statusColor[ws.status] ?? "text-neutral-500"}`}
              />
              <span className="truncate">{ws.name}</span>
            </button>
          ))}

          {workspaces.length === 0 && (
            <p className="px-3 py-2 text-xs text-neutral-500">
              No workspaces yet
            </p>
          )}

          <div className="border-t border-neutral-700 mt-1 pt-1">
            <button
              onClick={handleAddWorkspace}
              className="flex w-full items-center gap-2 px-3 py-2 text-sm text-neutral-400 hover:bg-neutral-700 hover:text-neutral-200 transition-colors"
            >
              <Plus className="h-3.5 w-3.5" />
              <span>Add Workspace</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

interface DesktopBridge {
  getWsUrl: () => string | null;
  pickFolder: () => Promise<string | null>;
}

type DesktopWindow = typeof window & { desktopBridge: DesktopBridge };

// src/components/sidebar/WorkspaceSwitcher.svelte
<script lang="ts">
  import { ChevronDown, Cog, Plus } from "@lucide/svelte";
  import type { WorkspaceStatus, DisplayWorkspace } from "../../stores/types";
  import { Mono } from "../../lib/primitives";

  interface Props {
    workspaces: DisplayWorkspace[];
    selectedId: string | null;
    onSelect: (id: string) => void;
    onOpenWorkspaceSettings: () => void;
    onCreateWorkspace: () => void;
    onOpenOverview: () => void;
    overviewActive?: boolean;
  }

  let {
    workspaces,
    selectedId,
    onSelect,
    onOpenWorkspaceSettings,
    onCreateWorkspace,
    onOpenOverview,
    overviewActive = false,
  }: Props = $props();

  let open = $state(false);
  let rootEl: HTMLDivElement | undefined = $state();

  const current = $derived(
    (workspaces.find((w) => w.id === selectedId) ?? workspaces[0]) as
      | DisplayWorkspace
      | undefined,
  );

  function statusDotClass(s: WorkspaceStatus) {
    return s.state === "error" ? "bg-error" : "bg-success";
  }

  function statusLabel(s: WorkspaceStatus) {
    return s.state === "error" ? "Error" : "Ready";
  }

  $effect(() => {
    if (!open) return;
    function onDoc(e: MouseEvent) {
      const t = e.target;
      if (!(t instanceof Node)) return;
      if (rootEl && !rootEl.contains(t)) {
        open = false;
      }
    }
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") open = false;
    }
    document.addEventListener("mousedown", onDoc);
    document.addEventListener("keydown", onKey);
    return () => {
      document.removeEventListener("mousedown", onDoc);
      document.removeEventListener("keydown", onKey);
    };
  });
</script>

{#if current}
  <div
    bind:this={rootEl}
    class="relative flex items-stretch gap-[2px] rounded-[7px] transition-colors"
    class:bg-bg-selected={open || overviewActive}
  >
    <button
      type="button"
      class="flex min-w-0 flex-1 items-center gap-2 rounded-[7px] px-[6px] py-[6px] text-left transition-colors
        {open || overviewActive ? '' : 'hover:bg-bg-hover'}"
      title="Workspace overview"
      onclick={onOpenOverview}
    >
      <span
        class="size-5 shrink-0 rounded-[5px] bg-fg-heading text-bg-base flex items-center justify-center text-[11px] font-bold tracking-tight"
      >
        {current.name.charAt(0).toUpperCase()}
      </span>
      <span class="flex flex-1 min-w-0 items-center gap-1.5">
        <span
          class="min-w-0 flex-1 truncate text-[12.5px] font-semibold text-fg-heading"
          >{current.name}</span
        >
        <span
          class="size-1.5 shrink-0 rounded-full {statusDotClass(
            current.status,
          )}"
          title={statusLabel(current.status)}
        ></span>
      </span>
    </button>
    <button
      type="button"
      class="inline-flex shrink-0 items-center justify-center rounded-[7px] px-[6px] text-fg-disabled transition-colors
        {open || overviewActive ? '' : 'hover:bg-bg-hover'}"
      title="Switch workspace"
      aria-expanded={open}
      aria-haspopup="listbox"
      onclick={() => (open = !open)}
    >
      <ChevronDown size={10} />
    </button>
    {#if open}
      <div
        class="absolute top-[calc(100%+6px)] left-0 z-10 w-[260px] rounded-[10px] border border-border-strong bg-bg-elevated p-[6px] shadow-[var(--shadow-lg)]"
        role="presentation"
        onclick={(e) => e.stopPropagation()}
      >
        {#each workspaces as w (w.id)}
          {@const sel = w.id === selectedId}
          <button
            type="button"
            class="flex w-full items-center gap-2.5 rounded-[6px] px-2 py-[7px] text-left text-[12.5px] transition-colors
              {sel
              ? 'bg-bg-selected text-fg-heading hover:brightness-[0.99]'
              : 'text-fg-default hover:bg-bg-hover'}"
            onclick={() => {
              onSelect(w.id);
              open = false;
            }}
          >
            <span
              class="size-5 shrink-0 rounded-[5px] bg-fg-heading text-bg-base flex items-center justify-center text-[11px] font-bold"
              >{w.name.charAt(0).toUpperCase()}</span
            >
            <span class="min-w-0 flex-1 truncate">{w.name}</span>
            <Mono class="!font-normal !capitalize text-fg-disabled" size={10}
              >{statusLabel(w.status)}</Mono
            >
          </button>
        {/each}
        <div class="h-px bg-border-default my-[6px] mx-[2px]"></div>
        <button
          type="button"
          class="flex w-full items-center gap-2.5 rounded-[6px] px-2 py-[7px] text-left text-[12.5px] text-fg-muted transition-colors hover:bg-bg-hover"
          onclick={() => {
            onOpenWorkspaceSettings();
            open = false;
          }}
        >
          <Cog size={11} />
          <span>Workspace settings</span>
        </button>
        <button
          type="button"
          class="flex w-full items-center gap-2.5 rounded-[6px] px-2 py-[7px] text-left text-[12.5px] text-fg-muted transition-colors hover:bg-bg-hover"
          onclick={() => {
            onCreateWorkspace();
            open = false;
          }}
        >
          <Plus size={11} />
          <span>New workspace</span>
        </button>
      </div>
    {/if}
  </div>
{/if}
